{
 "title": "Validators",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Consensus Status",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "validator_inconsensus" }
   ]
  },
  {
   "title": "Performance Penalty",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "validator_ledger{subtype=\"performance\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Tenure",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "validator_ledger{subtype=\"tenure\"}",
     "legendFormat": "{{validator_name}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=~\".*-validator:9100\"}"
    }
   ]
  },
  {
   "title": "Block Rate/min",
   "type": "gauge",
   "description": "Block chain block production rate, per minute.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(validator_height[5m])*60" }
   ]
  },
  {
   "title": "HBBFT BBA Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_hbbft_perf{subtype=~\"BBA_Total|BBA_Votes\"}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "HBBFT Seen Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_hbbft_perf{subtype=~\"Seen_Votes|Seen_Total\"}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\".*-validator:9100\",device=~\"ens.*\"}[2m])*8",
     "legendFormat": "inbound"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\".*-validator:9100\",device=~\"ens.*\"}[2m])*8",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_api_balance", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_height" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\".*-validator:9100\"}",
     "legendFormat": "massive-metal-mamoth"
    }
   ]
  },
  {
   "title": "CPU Steal",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{instance=~\".*-validator:9100\",job=\"node\",mode=\"steal\"}[5m]) * 100))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Wait",
   "type": "graph",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=~\".*-validator:9100\",mode=\"iowait\"}[5m])*100",
     "legendFormat": "cpu-{{cpu}}"
    }
   ]
  },
  {
   "title": "Penalty",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_ledger{subtype=~\"performance|tenure\"}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_inconsensus" }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\".*-validator:9100\"}",
     "legendFormat": "validator-free"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\".*-validator:9100\"}",
     "legendFormat": "validator-available"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\".*-validator:9100\",mountpoint=\"/home\"}",
     "legendFormat": "validator-{{mountpoint}}"
    }
   ]
  }
 ]
}